export const IPC_CHANNELS = {
  createMember: 'member:create',
  listMembers: 'member:list',
  executeBuy: 'transaction:buy',
  executeSell: 'transaction:sell',
  executeDividend: 'transaction:dividend',
  reverseTransaction: 'transaction:reverse',
  executeWithdrawCash: 'transaction:withdraw',
  executeStockBonus: 'transaction:stockbonus',
  executeMemberExit: 'member:exit',
  listTransactions: 'transaction:list',
  listTransactionDetails: 'transaction:details',
  getPublicAccount: 'account:latest',
  getHistoricalSnapshot: 'account:history-snapshot',
  validateReplay: 'account:validate-replay',
  getTradingConfig: 'config:trading:get',
  updateTradingConfig: 'config:trading:update',
} as const;
